const $=id=>document.getElementById(id),title=$('title'),content=$('content'),category=$('category'),grid=$('notesGrid'),empty=$('empty'),search=$('search'),filter=$('filter');let editId=null;const NOTES='notes-app-notes',DRAFT='notes-app-draft',THEME='notes-app-theme';
function safeParse(raw,fallback){try{return raw?JSON.parse(raw):fallback}catch{return fallback}}const getNotes=()=>safeParse(localStorage.getItem(NOTES),[]);const setNotes=n=>localStorage.setItem(NOTES,JSON.stringify(n));function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateStats(){const n=getNotes();$('noteCount').textContent=n.length;$('pinCount').textContent=n.filter(x=>x.pinned).length;$('charCount').textContent=n.reduce((a,x)=>a+(x.content||'').length,0).toLocaleString()}
function render(){const q=search.value.trim().toLowerCase(),cat=filter.value;let notes=getNotes().filter(n=>(cat==='all'||n.category===cat)&&((n.title+' '+n.content).toLowerCase().includes(q)));notes.sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||new Date(b.updatedAt)-new Date(a.updatedAt));grid.innerHTML='';empty.style.display=notes.length?'none':'block';$('resultText').textContent=`${notes.length} ${notes.length===1?'note':'notes'}`;notes.forEach(n=>{const d=document.createElement('article');d.className='note';d.innerHTML=`<div class="noteTop"><span class="badge">${esc(n.category||'Other')}</span><button class="pin ${n.pinned?'active':''}" data-pin="${n.id}" title="Pin note">★</button></div><h3>${esc(n.title)}</h3><p>${esc(n.content)}</p><div class="noteFoot"><span class="meta">${new Date(n.updatedAt).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span><div class="actions"><button data-edit="${n.id}">Edit</button><button class="danger" data-delete="${n.id}">Delete</button></div></div>`;grid.appendChild(d)});updateStats()}
function saveDraft(){sessionStorage.setItem(DRAFT,JSON.stringify({title:title.value,content:content.value,category:category.value}));$('draftStatus').textContent=(title.value||content.value)?'Saved':'Ready';$('counter').textContent=`${content.value.length} / 2000`}
function clearForm(){title.value='';content.value='';category.value='Study';editId=null;sessionStorage.removeItem(DRAFT);$('saveBtn').textContent='Save note';$('formHeading').textContent='New note';saveDraft()}
$('saveBtn').onclick=()=>{if(!title.value.trim()||!content.value.trim())return alert('Please enter both a title and note.');let notes=getNotes(),now=new Date().toISOString();if(editId)notes=notes.map(n=>n.id===editId?{...n,title:title.value.trim(),content:content.value.trim(),category:category.value,updatedAt:now}:n);else notes.unshift({id:crypto.randomUUID?.()||String(Date.now()),title:title.value.trim(),content:content.value.trim(),category:category.value,pinned:false,createdAt:now,updatedAt:now});setNotes(notes);clearForm();render()};$('clearBtn').onclick=clearForm;[title,content,category].forEach(e=>e.addEventListener('input',saveDraft));search.oninput=render;filter.onchange=render;
grid.onclick=e=>{const del=e.target.dataset.delete,edit=e.target.dataset.edit,pin=e.target.dataset.pin,id=del||edit||pin;if(!id)return;if(del){if(confirm('Delete this note?'))setNotes(getNotes().filter(n=>n.id!==id))}else if(pin){setNotes(getNotes().map(n=>n.id===id?{...n,pinned:!n.pinned,updatedAt:new Date().toISOString()}:n))}else{const n=getNotes().find(n=>n.id===id);title.value=n.title;content.value=n.content;category.value=n.category||'Other';editId=id;$('saveBtn').textContent='Update note';$('formHeading').textContent='Edit note';saveDraft();$('notes').scrollIntoView({behavior:'smooth'})}render()};
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME,document.body.classList.contains('dark')?'dark':'light');$('themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'};if(localStorage.getItem(THEME)==='dark'){document.body.classList.add('dark');$('themeBtn').textContent='☀'}
function all(s){const o={};for(let i=0;i<s.length;i++){const k=s.key(i);o[k]=s.getItem(k)}return o}document.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>{const local=b.dataset.store==='local',s=local?localStorage:sessionStorage,p=local?'local':'session',k=$(p+'Key').value,v=$(p+'Value').value,out=$(p+'Out'),a=b.dataset.act;if(a==='set'){if(!k)return out.textContent='Enter a key first.';s.setItem(k,v);out.textContent=`Saved: ${k} = ${v}`}if(a==='get')out.textContent=k?`${k} = ${s.getItem(k)}`:'Enter a key first.';if(a==='remove'){if(!k)return out.textContent='Enter a key first.';s.removeItem(k);out.textContent=`Removed: ${k}`}if(a==='show')out.textContent=JSON.stringify(all(s),null,2);updateStats()});
$('stringifyBtn').onclick=()=>{try{$('jsonOut').textContent=JSON.stringify(JSON.parse($('jsonInput').value),null,2)}catch(e){$('jsonOut').textContent='Invalid JSON: '+e.message}};$('parseBtn').onclick=()=>{try{const obj=JSON.parse($('jsonInput').value);$('jsonOut').textContent=`Parsed successfully (${Array.isArray(obj)?'array':typeof obj}):
`+JSON.stringify(obj,null,2)}catch(e){$('jsonOut').textContent='Parse error: '+e.message}};$('jsonLocalBtn').onclick=()=>{try{const obj=JSON.parse($('jsonInput').value);localStorage.setItem('json-playground-object',JSON.stringify(obj));$('jsonOut').textContent='Saved under key "json-playground-object".'}catch(e){$('jsonOut').textContent='Invalid JSON: '+e.message}};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(getNotes(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='notespace-notes.json';a.click();URL.revokeObjectURL(a.href)};$('importFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data))throw Error('Expected an array of notes');const now=new Date().toISOString(),clean=data.filter(x=>x&&x.title&&x.content).map((x,i)=>({...x,id:x.id||String(Date.now()+i),category:x.category||'Other',pinned:!!x.pinned,createdAt:x.createdAt||now,updatedAt:x.updatedAt||now}));setNotes(clean);render();alert(`Imported ${clean.length} notes.`)}catch(err){alert('Could not import: '+err.message)}e.target.value=''};
const draft=safeParse(sessionStorage.getItem(DRAFT),null);if(draft){title.value=draft.title||'';content.value=draft.content||'';category.value=draft.category||'Study'}saveDraft();render();